-- MySQL Script generated by MySQL Workbench
-- Fri Sep  7 00:46:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eurovision
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eurovision` ;

-- -----------------------------------------------------
-- Schema eurovision
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eurovision` DEFAULT CHARACTER SET utf8 ;
USE `eurovision` ;

-- -----------------------------------------------------
-- Table `eurovision`.`Zemja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eurovision`.`Zemja` ;

CREATE TABLE IF NOT EXISTS `eurovision`.`Zemja` (
  `ime` VARCHAR(50) NOT NULL,
  `region` VARCHAR(30) NULL,
  PRIMARY KEY (`ime`),
  INDEX `region_idx` (`region` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eurovision`.`Godina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eurovision`.`Godina` ;

CREATE TABLE IF NOT EXISTS `eurovision`.`Godina` (
  `godina` INT NOT NULL,
  `zemjaDomakjin` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`godina`),
  UNIQUE INDEX `godina_UNIQUE` (`godina` ASC) VISIBLE,
  INDEX `zemjaDomakjin_idx` (`zemjaDomakjin` ASC) VISIBLE,
  CONSTRAINT `fk_godina_zemjaDomakjin`
    FOREIGN KEY (`zemjaDomakjin`)
    REFERENCES `eurovision`.`Zemja` (`ime`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eurovision`.`EvroviziskaVecher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eurovision`.`EvroviziskaVecher` ;

CREATE TABLE IF NOT EXISTS `eurovision`.`EvroviziskaVecher` (
  `godina` INT NOT NULL,
  `tip` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`godina`, `tip`),
  CONSTRAINT `fk_evroviziskavecher_godina`
    FOREIGN KEY (`godina`)
    REFERENCES `eurovision`.`Godina` (`godina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ck_evroviziskavecher_tip`
	CHECK (`tip` IN ("SF1","SF2","F")))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eurovision`.`Izveduvach`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eurovision`.`Izveduvach` ;

CREATE TABLE IF NOT EXISTS `eurovision`.`Izveduvach` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(50) NULL,
  `tip` VARCHAR(10) NULL,
  `pol` VARCHAR(10) NULL,
  `zemjaPoteklo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `zemjaPoteklo_idx` (`zemjaPoteklo` ASC) INVISIBLE,
  INDEX `ime_idx` (`ime` ASC) VISIBLE,
  INDEX `pol_idx` (`pol` ASC) INVISIBLE,
  INDEX `tip_idx` (`tip` ASC) VISIBLE,
  CONSTRAINT `fk_izveduvach_zemjaPoteklo`
    FOREIGN KEY (`zemjaPoteklo`)
    REFERENCES `eurovision`.`Zemja` (`ime`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ck_izveduvach_tip`
	CHECK (`tip` IN ("Group","Solo")),
  CONSTRAINT `ck_izveduvach_pol`
	CHECK (`pol` IN ("Male","Female","Both")))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eurovision`.`Pesna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eurovision`.`Pesna` ;

CREATE TABLE IF NOT EXISTS `eurovision`.`Pesna` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(50) NULL,
  `imeAngliski` VARCHAR(50) NULL,
  `avtor` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `avtor_idx` (`avtor` ASC) VISIBLE,
  INDEX `ime_idx` (`ime` ASC) INVISIBLE,
  CONSTRAINT `fk_pesna_avtor`
    FOREIGN KEY (`avtor`)
    REFERENCES `eurovision`.`Izveduvach` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eurovision`.`Glasanje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eurovision`.`Glasanje` ;

CREATE TABLE IF NOT EXISTS `eurovision`.`Glasanje` (
  `zemja1` VARCHAR(50) NOT NULL,
  `zemja2` VARCHAR(50) NOT NULL,
  `godina` INT NOT NULL,
  `vecher` VARCHAR(20) NOT NULL,
  `poeni` INT NULL,
  PRIMARY KEY (`zemja1`, `zemja2`, `godina`, `vecher`),
  INDEX `fk_zemja2_idx` (`zemja2` ASC) INVISIBLE,
  INDEX `fk_godina_vecher_idx` (`godina` ASC, `vecher` ASC) VISIBLE,
  INDEX `fk_zemja1_idx` (`zemja1` ASC) INVISIBLE,
  INDEX `poeni_idx` (`poeni` ASC) VISIBLE,
  CONSTRAINT `fk_glasanje_zemja1`
    FOREIGN KEY (`zemja1`)
    REFERENCES `eurovision`.`Zemja` (`ime`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_glasanje_zemja2`
    FOREIGN KEY (`zemja2`)
    REFERENCES `eurovision`.`Zemja` (`ime`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_glasanje_godina_vecher`
    FOREIGN KEY (`godina` , `vecher`)
    REFERENCES `eurovision`.`EvroviziskaVecher` (`godina` , `tip`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ck_glasanje_zemji`
	CHECK (`zemja1` != `zemja2`),
  CONSTRAINT `ck_glasanje_poeni`
	CHECK (`poeni` IN (0,1,2,3,4,5,6,7,8,9,10,12)))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eurovision`.`Uchestvo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eurovision`.`Uchestvo` ;

CREATE TABLE IF NOT EXISTS `eurovision`.`Uchestvo` (
  `godina` INT NOT NULL,
  `vecher` VARCHAR(20) NOT NULL,
  `pesna` INT NOT NULL,
  `mesto` INT NULL,
  `poeni` INT NULL,
  `cenaOblozhuvanje` FLOAT NULL,
  PRIMARY KEY (`godina`, `vecher`, `pesna`),
  INDEX `fk_pesna_idx` (`pesna` ASC) INVISIBLE,
  INDEX `fk_godina_vecher_idx` (`godina` ASC, `vecher` ASC) VISIBLE,
  INDEX `mesto_poeni_idx` (`mesto` ASC, `poeni` ASC) VISIBLE,
  INDEX `cenaOblozhuvanje_idx` (`cenaOblozhuvanje` ASC) VISIBLE,
  CONSTRAINT `fk_uchestvo_godina_vecher`
    FOREIGN KEY (`godina` , `vecher`)
    REFERENCES `eurovision`.`EvroviziskaVecher` (`godina` , `tip`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_uchestvo_pesna`
    FOREIGN KEY (`pesna`)
    REFERENCES `eurovision`.`Pesna` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ck_uchestvo_mesto`
	CHECK (`mesto` BETWEEN 1 AND 26),
  CONSTRAINT `ck_uchestvo_poeni`
	CHECK (`poeni` >= 0),
  CONSTRAINT `ck_uchestvo_cenaOblozhuvanje`
    CHECK (`cenaOblozhuvanje` >= 0))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eurovision`.`PesnaJazik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eurovision`.`PesnaJazik` ;

CREATE TABLE IF NOT EXISTS `eurovision`.`PesnaJazik` (
  `pesna` INT NOT NULL,
  `jazik` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`pesna`, `jazik`),
  CONSTRAINT `fk_pesnajazik_pesna`
    FOREIGN KEY (`pesna`)
    REFERENCES `eurovision`.`Pesna` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
